import { serve } from 'inngest/next';
import {
  inngest,
  processScheduledNotifications,
  onRsvpCreated,
  onRsvpCancelled,
  onRsvpInterested,
  onCommentCreated,
  dailyBlogSummary,
  dailyEventDiscovery,
  manualEventDiscovery,
  processMomentMetadata,
  processVideoWhenReady,
  processPendingMoments,
  reprocessMoment,
  // SEO Agent Swarm
  strategyCommander,
  keywordScout,
  newsHarvester,
  socialSentinel,
  eventIntelligence,
  pillarArchitect,
  contentForge,
  seoSurgeon,
  translationBackfill,
  visualAlchemist,
  qualityGate,
  distributionHub,
  analyticsOracle,
  internalLinker,
} from '@/lib/inngest';

// Create the Inngest API handler
export const { GET, POST, PUT } = serve({
  client: inngest,
  functions: [
    processScheduledNotifications,
    onRsvpCreated,
    onRsvpCancelled,
    onRsvpInterested,
    onCommentCreated,
    dailyBlogSummary,
    dailyEventDiscovery,
    manualEventDiscovery,
    // Moment AI processing
    processMomentMetadata,
    processVideoWhenReady,
    processPendingMoments,
    reprocessMoment,
    // SEO Agent Swarm (14 agents)
    strategyCommander,
    keywordScout,
    newsHarvester,
    socialSentinel,
    eventIntelligence,
    pillarArchitect,
    contentForge,
    seoSurgeon,
    translationBackfill,
    visualAlchemist,
    qualityGate,
    distributionHub,
    analyticsOracle,
    internalLinker,
  ],
});
