-- Expand content_translations field_name constraint to support
-- additional AI metadata fields for the SEO/AEO/GEO pipeline.
-- New fields: ai_title, video_transcript, audio_transcript, pdf_extracted_text
--
-- These fields are generated by the AI content analyzers (Inngest moment processing)
-- and translated to 12 languages for multilingual discoverability.

-- Drop the existing constraint and recreate with expanded field list
ALTER TABLE content_translations
  DROP CONSTRAINT IF EXISTS content_translations_field_name_check;

ALTER TABLE content_translations
  ADD CONSTRAINT content_translations_field_name_check
  CHECK (field_name IN (
    -- Core content fields
    'title', 'description', 'text_content', 'bio',
    -- Blog fields
    'story_content', 'technical_content', 'meta_description',
    -- Image SEO fields
    'image_alt', 'image_description',
    -- AI metadata fields (summaries)
    'ai_description', 'ai_title', 'scene_description',
    'video_summary', 'audio_summary', 'pdf_summary',
    -- AI metadata fields (full transcripts/extracts)
    'video_transcript', 'audio_transcript', 'pdf_extracted_text',
    -- Comment content
    'content',
    -- Track/lyrics content
    'lyrics'
  ));
