-- Explicit Data API grants for tables created by earlier migrations.
--
-- Supabase stops granting new public tables to anon, authenticated and service_role
-- automatically on 2026-10-30. Existing tables on the hosted project keep the grants they
-- have, so this migration changes nothing there. It makes a database built from these
-- migrations without automatic grants (a preview branch, a new project, a local reset with
-- auto_expose_new_tables = false) match: each table gets what its RLS policies and server
-- code need, and every serial sequence behind a client insert gets usage.

grant select, insert, update, delete on public.profiles to service_role;
grant select, insert, update, delete on public.profiles to anon, authenticated;
grant select, insert, update, delete on public.tribes to service_role;
grant select, insert, update, delete on public.tribes to anon, authenticated;
grant select, insert, update, delete on public.tribe_follows to service_role;
grant select, insert, delete on public.tribe_follows to anon, authenticated;
grant select, insert, update, delete on public.events to service_role;
grant select, insert, update, delete on public.events to anon, authenticated;
grant select, insert, update, delete on public.rsvps to service_role;
grant select, insert, update, delete on public.rsvps to anon, authenticated;
grant select, insert, update, delete on public.rsvp_cancellations to service_role;
grant select, insert on public.rsvp_cancellations to anon, authenticated;
grant select, insert, update, delete on public.organizers to service_role;
grant select, insert, update, delete on public.organizers to anon, authenticated;
grant select, insert, update, delete on public.push_subscriptions to service_role;
grant select, insert, update, delete on public.push_subscriptions to anon, authenticated;
grant select, insert, update, delete on public.verification_requests to service_role;
grant select, insert, update, delete on public.verification_requests to anon, authenticated;
grant select, insert, update, delete on public.festivals to service_role;
grant select, insert, update, delete on public.festivals to anon, authenticated;
grant select, insert, update, delete on public.festival_organizers to service_role;
grant select, insert, delete on public.festival_organizers to anon, authenticated;
grant select, insert, update, delete on public.festival_events to service_role;
grant select, insert, update, delete on public.festival_events to anon, authenticated;
grant select, insert, update, delete on public.festival_updates to service_role;
grant select, insert, update, delete on public.festival_updates to anon, authenticated;
grant select, insert, update, delete on public.event_settings to service_role;
grant select, insert, update on public.event_settings to anon, authenticated;
grant select, insert, update, delete on public.moments to service_role;
grant select, insert, update, delete on public.moments to anon, authenticated;
grant select, insert, update, delete on public.login_events to service_role;
grant select, insert, update, delete on public.login_events to anon, authenticated;
grant select, insert, update, delete on public.moment_likes to service_role;
grant select on public.moment_likes to anon;
grant select, insert, delete on public.moment_likes to authenticated;
grant select, insert, update, delete on public.event_invitations to service_role;
grant select, insert, update, delete on public.event_invitations to anon, authenticated;
grant select, insert, update, delete on public.organizer_contacts to service_role;
grant select, insert, update, delete on public.organizer_contacts to anon, authenticated;
grant select, insert, update, delete on public.invite_quotas to service_role;
grant select on public.invite_quotas to anon, authenticated;
grant select, insert, update, delete on public.event_series to service_role;
grant select, insert, update, delete on public.event_series to anon, authenticated;
grant select, insert, update, delete on public.series_exceptions to service_role;
grant select, insert, update, delete on public.series_exceptions to anon, authenticated;
grant select, insert, update, delete on public.series_rsvps to service_role;
grant select, insert, update, delete on public.series_rsvps to anon, authenticated;
grant select, insert, update, delete on public.tribe_members to service_role;
grant select, insert, update, delete on public.tribe_members to anon, authenticated;
grant select, insert, update, delete on public.tribe_requests to service_role;
grant select, insert, update on public.tribe_requests to anon, authenticated;
grant select, insert, update, delete on public.venue_managers to service_role;
grant select, insert, update, delete on public.venue_managers to anon, authenticated;
grant select, insert, update, delete on public.sponsors to service_role;
grant select on public.sponsors to anon;
grant select, insert, update, delete on public.sponsors to authenticated;
grant select, insert, update, delete on public.event_sponsors to service_role;
grant select on public.event_sponsors to anon;
grant select, insert, update, delete on public.event_sponsors to authenticated;
grant select, insert, update, delete on public.content_translations to service_role;
grant select, insert, update, delete on public.content_translations to anon, authenticated;
grant select, insert, update, delete on public.tribe_contacts to service_role;
grant select, insert, update, delete on public.tribe_contacts to anon, authenticated;
grant select, insert, update, delete on public.contact_invites to service_role;
grant select, insert, update, delete on public.contact_invites to anon, authenticated;
grant select, insert, update, delete on public.rate_limits to service_role;
grant select, insert, update, delete on public.rate_limits to anon, authenticated;
grant select, insert, update, delete on public.event_feedback to service_role;
grant select, insert, update on public.event_feedback to anon, authenticated;
grant select, insert, update, delete on public.impersonation_sessions to service_role;
grant select, insert, update, delete on public.blog_categories to service_role;
grant select on public.blog_categories to anon;
grant select, insert, update, delete on public.blog_categories to authenticated;
grant select, insert, update, delete on public.blog_posts to service_role;
grant select on public.blog_posts to anon;
grant select, insert, update, delete on public.blog_posts to authenticated;
grant select, insert, update, delete on public.blog_post_likes to service_role;
grant select on public.blog_post_likes to anon;
grant select, insert, delete on public.blog_post_likes to authenticated;
grant select, insert, update, delete on public.live_streams to service_role;
grant select, insert, update, delete on public.live_streams to anon, authenticated;
grant select, insert, update, delete on public.stream_chat_messages to service_role;
grant select, update on public.stream_chat_messages to anon;
grant select, insert, update on public.stream_chat_messages to authenticated;
grant select, insert, update, delete on public.personas to service_role;
grant select, insert, update, delete on public.personas to anon, authenticated;
grant select, insert, update, delete on public.notifications to service_role;
grant select, update, delete on public.notifications to authenticated;
grant select, insert, update, delete on public.notification_preferences to service_role;
grant select, insert, update on public.notification_preferences to authenticated;
grant select, insert, update, delete on public.scheduled_notifications to service_role;
grant select, insert, update, delete on public.moment_embeddings to service_role;
grant select on public.moment_embeddings to anon, authenticated;
grant select, insert, update, delete on public.venues to service_role;
grant select, insert, update, delete on public.venues to anon, authenticated;
grant select, insert, update, delete on public.comments to service_role;
grant select on public.comments to anon;
grant select, insert, update, delete on public.comments to authenticated;
grant select, insert, update, delete on public.muted_threads to service_role;
grant select, insert, update, delete on public.muted_threads to authenticated;
grant select, insert, update, delete on public.homepage_config to service_role;
grant select, insert, update on public.homepage_config to anon, authenticated;
grant select, insert, update, delete on public.event_materials to service_role;
grant select on public.event_materials to anon;
grant select, insert, update, delete on public.event_materials to authenticated;
grant select, insert, update, delete on public.unified_slugs to service_role;
grant select, insert, update, delete on public.unified_slugs to anon, authenticated;
grant select, insert, update, delete on public.reserved_slugs to service_role;
grant select, insert on public.reserved_slugs to anon, authenticated;
grant select, insert, update, delete on public.unified_slug_migration_conflicts to service_role;
grant select on public.unified_slug_migration_summary to service_role;
grant select, insert, update, delete on public.image_versions to service_role;
grant select, insert, delete on public.image_versions to anon, authenticated;
grant select, insert, update, delete on public.event_playlists to service_role;
grant select, insert, update, delete on public.event_playlists to anon, authenticated;
grant select, insert, update, delete on public.playlist_tracks to service_role;
grant select, insert, update, delete on public.playlist_tracks to anon, authenticated;
grant select, insert, update, delete on public.promo_media to service_role;
grant select, insert, update, delete on public.promo_media to anon, authenticated;
grant select, insert, update, delete on public.question_templates to service_role;
grant select on public.question_templates to anon, authenticated;
grant select, insert, update, delete on public.event_questionnaires to service_role;
grant select, insert, update, delete on public.event_questionnaires to anon, authenticated;
grant select, insert, update, delete on public.event_questions to service_role;
grant select, insert, update, delete on public.event_questions to anon, authenticated;
grant select, insert, update, delete on public.rsvp_responses to service_role;
grant select, insert, update on public.rsvp_responses to anon, authenticated;
grant select, insert, update, delete on public.user_follows to service_role;
grant select, insert, delete on public.user_follows to anon, authenticated;
grant select, insert, update, delete on public.native_push_tokens to service_role;
grant select, insert, update, delete on public.native_push_tokens to anon, authenticated;
grant select, insert, update, delete on public.plus_one_guests to service_role;
grant select, insert, update, delete on public.plus_one_guests to anon, authenticated;
grant select, insert, update, delete on public.news_raw_articles to service_role;
grant select, insert, update, delete on public.user_loyalty_status to service_role;
grant select on public.user_loyalty_status to anon, authenticated;
grant select, insert, update, delete on public.loyalty_point_transactions to service_role;
grant select on public.loyalty_point_transactions to anon, authenticated;
grant select, insert, update, delete on public.loyalty_tier_history to service_role;
grant select on public.loyalty_tier_history to anon, authenticated;
grant select, insert, update, delete on public.rewards to service_role;
grant select, insert, update, delete on public.rewards to anon, authenticated;
grant select, insert, update, delete on public.reward_redemptions to service_role;
grant select, update on public.reward_redemptions to anon, authenticated;
grant select, insert, update, delete on public.host_rewards to service_role;
grant select, update on public.host_rewards to anon, authenticated;
grant select, insert, update, delete on public.loyalty_experiments to service_role;
grant select, insert, update, delete on public.loyalty_experiments to anon, authenticated;
grant select, insert, update, delete on public.loyalty_experiment_assignments to service_role;
grant select, insert, update, delete on public.loyalty_experiment_assignments to anon, authenticated;
grant select, insert, update, delete on public.workshop_answers to service_role;
grant select, insert, update, delete on public.phuong_members to service_role;
grant select, insert, update, delete on public.phuong_plan to service_role;
grant select, insert, update, delete on public.phuong_actions to service_role;
grant select, insert, update, delete on public.phuong_idea_votes to service_role;
grant select, insert, update, delete on public.experiences to service_role;
grant select on public.experiences to anon;
grant select, insert on public.experiences to authenticated;
grant select, insert, update, delete on public.experience_sources to service_role;
grant select on public.experience_sources to authenticated;
grant select, insert, update, delete on public.experience_media to service_role;
grant select on public.experience_media to anon, authenticated;
grant select, insert, update, delete on public.experience_venue_submissions to service_role;
grant select on public.experience_venue_submissions to authenticated;
grant select, insert, update, delete on public.seed_profiles to service_role;
grant select, insert, update, delete on public.import_runs to service_role;
grant select, insert, update, delete on public.event_private_details to service_role;
grant select, insert, update, delete on public.event_private_details to anon, authenticated;
grant select, insert, update, delete on public.content_pipeline_events to service_role;
grant select, insert, update, delete on public.import_queue to service_role;
grant select, insert, update, delete on public.image_jobs to service_role;
grant select on public.image_jobs to anon, authenticated;
grant select, insert, update, delete on public.worker_heartbeats to service_role;
grant select, insert, update, delete on public.reactions to service_role;
grant select on public.reactions to anon;
grant select, insert, delete on public.reactions to authenticated;
grant select, insert, update, delete on public.tribe_invitations to service_role;
grant select, insert, update, delete on public.tribe_invitations to anon, authenticated;
grant select, insert, update, delete on public.tribe_invite_quotas to service_role;
grant select on public.tribe_invite_quotas to anon, authenticated;
grant select, insert, update, delete on public.caption_jobs to service_role;
grant select, insert, update, delete on public.activity_sources to service_role;
grant select, insert, update, delete on public.activity_observations to service_role;
grant select, insert, update, delete on public.activity_candidates to service_role;
grant select, insert, update, delete on public.activity_evidence to service_role;
grant select, insert, update, delete on public.activity_canonical_links to service_role;
grant select, insert, update, delete on public.activity_merge_decisions to service_role;
grant select, insert, update, delete on public.activity_sync_leases to service_role;
